server:
  port: 13000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.5:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    hikari:
      max-lifetime: 1800000
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
  application:
    name: security-demo

jodconverter:
  local:
    enabled: true
    office-home: C:\Program Files\LibreOffice
    port-numbers: 8103,8105,8107
    max-tasks-per-process: 100